name: Python-Anwendung

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Bild erstellen und Image pushen
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u FrissBrot --password-stdin
        docker image build -t frissbrot/test:latest .
        docker push frissbrot/test:latest
